global.m = 3; //number of dots horizontally
global.n = 3; //number of dots vertically
global.current_player = 0;//blue go first
global.played = false;
global.vLine = ds_map_create();
global.vIdx = 0;
global.hLine = ds_map_create();
global.hIdx = 0;
global.Box = ds_grid_create(global.m, global.n)
global.line_played = [];