global.m = 2; //number of dots horizontally
global.n = 2; //number of dots vertically
global.current_player = 0;//blue go first
global.played = false;
global.vLine = ds_map_create();
global.empty_vLine = ds_map_create();
global.vIdx = 0;
global.hLine = ds_map_create();
global.empty_hLine = ds_map_create();
global.hIdx = 0;
global.Box = ds_grid_create(global.m, global.n)
global.line_played = [];
global.blue_score = 0;
global.red_score = 0;
global.validMoves = ds_list_create();
global.hValidMoves = 0;
global.vValidMoves = 0;